name = "qpackages-explorer"
main = "worker/index.ts"
compatibility_date = "2026-08-05"
workers_dev = true

[build]
command = "npm run build:wrangler"
watch_dir = ["src", "worker", "index.html", "vite.config.ts"]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = [
  "/corsbypass",
  "/corsbypass/*"
]

[observability]
enabled = true
